--
-- Generated by lua-china-regions(https://github.com/JustLikeCheese/lua-china-regions)
-- Created by JustLikeCheese
-- DateTime: 2025/4/17 10:52
--
local trie = require("trie")

local provinces = {
    province_data = require("assets/province_data"),
    province_index = {},
    province_names = {},
    province_trie = trie.new(),
    city_trie = trie.new(),
    city_index = {}
}

-- 初始化创建 Trie 树和索引表
for _, province in ipairs(provinces.province_data) do
    provinces.province_index[province.name] = province
    for _, city in ipairs(province.cities) do
        provinces.city_index[city] = province
        provinces.city_trie:insert(city, province)
    end
    provinces.province_trie:insert(province.name, province)
    table.insert(provinces.province_names, province.name)
end

function provinces.get_province(name)
    return provinces.province_index[name] or
               provinces.province_index[name .. "省"]
end

function provinces.get_province_by_city(name)
    return provinces.city_index[name] or provinces.city_index[name .. "市"] or
               provinces.city_index[name .. "县"] or
               provinces.city_index[name .. "区"]
end

function provinces.find_province(keyword)
    return {
        provinces.province_trie:search(keyword),
        provinces.city_trie:search(keyword)
    }
end

function provinces.get_province_names() return provinces.province_names end

function provinces.get_province_index() return provinces.province_index end

function provinces.get_city_index() return provinces.city_index end

return provinces
