--
-- Generated by lua-china-regions(https://github.com/JustLikeCheese/lua-china-regions)
-- Created by JustLikeCheese
-- DateTime: 2025/4/17 10:52
--

local trie = {}
trie.__index = trie

-- Trie Ê÷½Úµã
local trie_node = {}
trie_node.__index = trie_node

function trie_node.new()
    local self = setmetatable({}, trie_node)
    self.children = {}
    self.provinces = {}
    return self
end

-- Trie Ê÷
function trie.new()
    local self = setmetatable({}, trie)
    self.root = trie_node.new()
    return self
end

function trie:insert(word, province)
    local node = self.root
    for i = 1, #word do
        local char = word:sub(i, i)
        if not node.children[char] then
            node.children[char] = trie_node.new()
        end
        node = node.children[char]
        table.insert(node.provinces, province)
    end
end

function trie:search(prefix)
    local node = self.root
    for i = 1, #prefix do
        local char = prefix:sub(i, i)
        if not node.children[char] then return {} end
        node = node.children[char]
    end
    return node.provinces
end

return trie
